### ISSUE TITLE
Create a folder for each programming language

### ISSUE THREAD

**Issue by iambijayd** [thakurRashmi/Begineer_Friendly_Programs#82]
Hi there! The repository looks messy as there are all programs in one place. How about creating a separate folder for each programming language? If you agree, assign me the task I'm willing to help.

**Comment by thakurRashmi** [comment]
Hello,
Great Idea, sounds good. Go ahead with the task.
All the best:)

**Comment by thakurRashmi** [comment]
Great Work. Well done:))

**Comment by iambijayd** [comment]
Happy to help:)
